@port = 3000

### Get users
POST http://{{host}}:{{port}}/graphql
Content-Type: "application/json"

{"query": 
  "query {users {id,name}}", 
  "variables":null
}


### Add user
POST http://{{host}}:{{port}}/graphql
Content-Type: "application/json"

{"query":  
  "mutation {addUser(name:\"Shailen\") {id,name}}",
  "variables":null
}
